### ISSUE TITLE
Support for new API Gateway HTML

### ISSUE THREAD

**Issue by mcuervoe** [akrylysov/algnhsa#24]
AWS has announced the new [API Gateway HTML](https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/). It would be great if the algnhsa framework support this new API Gateway to take advantage of the advantages (less cost and less latency)

**Comment by akrylysov** [comment]
Have you tried setting the payload format version to 1 (https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)? It seems the new HTTP API is compatible with the old one.

**Comment by a-h** [comment]
I've tested it by using both V1 and V2 of the payload and neither worked for me.

I tried adding some logging to `algnhsa` to find out where it was going wrong and found that `lambda.StartHandler` was being called, but that a service unavailable was returned from Lambda, and the HTTP Handler was never actually called.

I used a module redirect to point to a local fork, and bumped `aws-lambda-go` version from v1.9.0 to v1.27.0 which fixed it immediately.

**Comment by a-h** [comment]
The structure of V1 and V2 requests is slightly different, so it needs another adapter, which I've included in the PR.

The V1 event type doesn't have the "version" field in it which allows differentiation between V1 and V2 responses, so the V2 event has to be checked prior to V1, rather than checking V1 and failing back to V2.
